# Generated by Django 5.0.7 on 2024-07-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
